---
version: "2.0"

services:
  web:
    image: bala150/crypto-converter:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 256Mi
        storage:
          size: 512Mi

  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    dcloud:
      profile: web
      count: 1
