name: Deploy to Akash

on:
  push:
    branches:
      - main  # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t bala150/crypto-converter:latest .
          docker push bala150/crypto-converter:latest

      - name: Install Akash CLI  # 🚀 Fix: Add this step
        run: |
          curl -sSL https://raw.githubusercontent.com/ovrclk/akash/master/install.sh | bash
          echo "$HOME/.akash/bin" >> $GITHUB_PATH

      - name: Import Akash Wallet  # ✅ Fix: Add wallet recovery step
        env:
          WALLET_KEY: ${{ secrets.AKASH_KEY }}
        run: |
          echo "$WALLET_KEY" | akash keys add mywallet --recover --keyring-backend test

      - name: Deploy to Akash  # ✅ Fix: Proper deployment command
        env:
          AKASH_KEYRING_BACKEND: test
          AKASH_CHAIN_ID: akashnet-2
          AKASH_NODE: https://rpc.akash.forbole.com:443
        run: |
          akash tx deployment create deploy.yml --from mywallet --node $AKASH_NODE --chain-id $AKASH_CHAIN_ID --yes
