name: Deploy to Akash

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: bala150/crypto-converter:latest
      AKASH_WALLET_NAME: mywallet
      AKASH_WALLET_MNEMONIC: ${{ secrets.AKASH_WALLET_MNEMONIC }}
      AKASH_KEYRING_BACKEND: test
      AKASH_CHAIN_ID: akashnet-2
      AKASH_NODE: https://rpc.akash.forbole.com:443

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Install Akash CLI
        run: |
          curl -LO https://github.com/akash-network/node/releases/download/v0.38.2/akash_0.38.2_Linux_amd64.deb
          sudo dpkg -i akash_0.38.2_Linux_amd64.deb
          akash version

      - name: Restore Akash Wallet from Mnemonic
        run: |
          echo "$AKASH_WALLET_MNEMONIC" | akash keys add "$AKASH_WALLET_NAME" --recover --keyring-backend "$AKASH_KEYRING_BACKEND"
          akash keys list --keyring-backend "$AKASH_KEYRING_BACKEND"

      - name: Deploy to Akash
        run: |
          akash tx deployment create deploy.yml \
            --from $AKASH_WALLET_NAME \
            --keyring-backend $AKASH_KEYRING_BACKEND \
            --node $AKASH_NODE \
            --chain-id $AKASH_CHAIN_ID \
            --gas-prices 0.025uakt \
            --gas auto \
            --gas-adjustment 1.5 \
            -y
