name: Deploy to Akash

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$Naveen@150" | docker login -u "bala150" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t bala150/crypto-converter:latest .
          docker push bala150/crypto-converter:latest

      - name: Deploy to Akash
        env:
          AKASH_KEYRING_BACKEND: test
          AKASH_CHAIN_ID: akashnet-2
          AKASH_NODE: https://rpc.akash.forbole.com:443
          WALLET_ADDRESS: ${{ secrets.AKASH_WALLET }}
          WALLET_KEY: ${{ secrets.AKASH_KEY }}
        run: |
          akash tx deployment create deploy.yaml --from $WALLET_ADDRESS
